package interpreter;

public final class Types {
    public static final int PROGRAM = 1;
    public static final int BEGIN = 2;
    public static final int END = 3;
    public static final int INT = 4;
    public static final int IF = 5;
    public static final int THEN = 6;
    public static final int ELSE = 7;
    public static final int WHILE = 8;
    public static final int LOOP = 9;
    public static final int READ = 10;
    public static final int WRITE = 11;
    public static final int SEMICOLON = 12;
    public static final int COMMA = 13;
    public static final int ASSIGN = 14;
    public static final int EXCLAMATION = 15;
    public static final int LEFT_BRACKET = 16;
    public static final int RIGHT_BRACKET = 17;
    public static final int AND = 18;
    public static final int OR = 19;
    public static final int LEFT_PAREN = 20;
    public static final int RIGHT_PAREN = 21;
    public static final int PLUS = 22;
    public static final int MINUS = 23;
    public static final int MULT = 24;
    public static final int NOT_EQUALS = 25;
    public static final int EQUALS = 26;
    public static final int LESS = 27;
    public static final int GREATER = 28;
    public static final int LESS_EQUAL = 29;
    public static final int GREATER_EQUAL = 30;
    public static final int INT_CONST = 31;
    public static final int ID = 32;
    public static final int EOF = 33;
    public static final int INVALID = 34;
    public static final int DIV = 35;
    public static final int EXP = 36;
    public static final int FOR = 37;
}
